inv.getResponse().setContentType("text/css")
pw = inv.getResponse().getWriter()
pw.println("@import url(https://fonts.googleapis.com/css?family=Overclock);")
pw.println("table {                                                        ")
pw.println("    border: thin solid gray;                                   ")
pw.println("    border-collapse: collapse;                                 ")
pw.println("}                                                              ")
pw.println("td {                                                           ")
pw.println("    border: thin solid gray;                                   ")
pw.println("    padding-left: 0.2em;                                       ")
pw.println("    padding-right: 0.2em;                                      ")
pw.println("}                                                              ")
pw.println("th {                                                           ")
pw.println("    border: thin solid gray;                                   ")
pw.println("}                                                              ")
pw.println("#title {                                                       ")
pw.println("    font-size: xx-large                                        ")
pw.println("}                                                              ")
pw.println(".logo {                                                        ")
pw.println("    color: green;                                              ")
pw.println("}                                                              ")
pw.println("                                                               ")
pw.println("                                                               ")
pw.println("                                                               ")
pw.println("                                                               ")
pw.println("body {                                                         ")
pw.println("    line-height: 1.2;                                          ")
pw.println("    font-size: 0.9em;                                          ")
pw.println("    font-family: 'Overclock', sans-serif;                      ")
pw.println("    background-color: rgb(255, 236, 139);                      ")
pw.println("}                                                              ")
pw.close()